default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: genixo_restoration_development

test:
  <<: *default
  database: genixo_restoration_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
